apiVersion: v1      # for versions before 1.9.0 use apps/v1beta2
kind: Service
metadata:
  name: card-validation
  labels:
    app: card-validation
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: card-validation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-validation-deployment
spec:
  selector:
    matchLabels:
      app: card-validation
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: card-validation
    spec:
      containers:
      - name: card-validation
        image: 
        ports:
        - containerPort: 80
