apiVersion: v1      # for versions before 1.9.0 use apps/v1beta2
kind: Service
metadata:
  name: LoadBalancer
  labels:
    app: 
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: 
        ports:
        - containerPort: 80
